import fs from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'
import {
  collectDocsEntries,
  extractComponentLinks,
  extractDocsEntries,
  renderAutocompleteDataFile,
} from '../../scripts/lib/akselDocs'

const FIXTURE_DIR = path.resolve('tests/fixtures/aksel-audit')

function readFixture(name: string): string {
  return fs.readFileSync(path.join(FIXTURE_DIR, name), 'utf8')
}

describe('Aksel docs helpers', () => {
  it('parses the llm index and linked markdown fixtures into merged docs entries', async () => {
    const llmDocs = readFixture('llm.md')
    const links = extractComponentLinks(llmDocs)
    const entries = await collectDocsEntries(llmDocs, async (link) => {
      const fileName = `${link.url.split('/').pop() ?? ''}`
      return readFixture(fileName)
    })

    expect(links.map((link) => link.title)).toEqual([
      'Combobox',
      'Page',
      'Navpoleonskake',
      'Typografi-komponenter',
    ])
    expect(entries.map((entry) => entry.name)).toEqual([
      'Combobox',
      'Ingress',
      'Navpoleonskake',
      'Page',
      'Page.Block',
    ])
    expect(entries.find((entry) => entry.name === 'Combobox')?.props).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ name: 'label', required: true }),
        expect.objectContaining({ name: 'multiple', values: ['false', 'true'] }),
        expect.objectContaining({ name: 'size', values: ['medium', 'small'] }),
      ])
    )
    expect(entries.find((entry) => entry.name === 'Page.Block')?.docs).toBe(
      'https://aksel.nav.no/komponenter/primitives/page'
    )
    expect(entries.find((entry) => entry.name === 'Navpoleonskake')?.props).toEqual([])
    expect(entries.find((entry) => entry.name === 'Ingress')?.status).toBe('deprecated')
  })

  it('parses standalone component sections and renders a generated data file with the new script header', () => {
    const comboboxEntries = extractDocsEntries(
      readFixture('combobox.md'),
      'https://aksel.nav.no/komponenter/core/combobox.md'
    )
    const fileSource = renderAutocompleteDataFile(comboboxEntries, [
      {
        name: 'aria-hidden',
        type: 'boolean',
        values: ['false', 'true'],
        required: false,
        description: 'SVG icon prop.',
      },
    ])

    expect(comboboxEntries).toHaveLength(1)
    expect(comboboxEntries[0].name).toBe('Combobox')
    expect(fileSource).toContain(
      '// Generated by scripts/generate-aksel-autocomplete-data.ts from https://aksel.nav.no/llm.md.'
    )
    expect(fileSource).toContain('export const AKSEL_AUTOCOMPLETE_ENTRIES')
    expect(fileSource).toContain('export const AKSEL_ICON_PROPS')
  })
})
